// Mutation operators for the public-safe guard, kept in the repo so a claimed
// mutation score can be re-derived by anyone.
//
// Independent review 16 (F16-07) could not reproduce the round-11 claim of
// "R15-01..R15-14, 14/14 KILLED": the artifact named the IDs, but the operators
// lived only in a throwaway script. A score whose operators are not written
// down is not a measurement.
//
// Anchors that need a literal backslash-u escape are BUILT FROM CHAR CODES.
// Writing them as escapes let a tool fold them into the real character, after
// which the operator reported PATCH-MISS -- which is the benign failure. The
// dangerous one is an anchor that stops matching for an unrelated reason and
// is then counted as KILLED. mutate.mjs treats any anchor count != 1 as a
// first-class failure for exactly that reason.
//
// Each entry may carry `file` (repo-relative); it defaults to
// project-config/evidence.js.
//
// Usage: node tools/guard-diff/mutate.mjs

const BS = String.fromCharCode(92);
const U = (hex) => BS + 'u' + hex;
const YEN = '[' + U('00a5') + U('ffe5') + ']';
const B2 = BS + BS;
const B3 = BS + BS + BS;
const SEP = '[' + B3 + '/]';          // [\\\/]  a separator class
const NOTSEP = '[^' + B3 + '/' + BS + 's]'; // [^\\\/\s]
const fold = (cls, extra) => 'text.replace(/' + cls + (extra || '') + "/g, '" + BS + BS + "')";

export const MUTANTS = [
  { id: 'M-01', describes: 'drive separator: forward slash dropped',
    find: 'pattern: /[A-Za-z]:' + SEP + '/',
    replace: 'pattern: /[A-Za-z]:[' + B2 + ']/' },
  { id: 'M-02', describes: 'drive letter: boundary re-added (the F16-01 hole)',
    find: 'pattern: /[A-Za-z]:' + SEP + '/',
    replace: 'pattern: /(^|[^A-Za-z0-9])[A-Za-z]:' + SEP + '/' },
  { id: 'M-03', describes: 'drive: currency carve-out re-introduced',
    find: 'pattern: /[A-Za-z]:' + SEP + '/',
    replace: 'pattern: /[A-Za-z]:' + SEP + '(?!(?:0|[1-9]' + BS + 'd{0,2})(?:,' + BS + 'd{3})*(?![' + BS + 'd' + BS + 'w.]))/' },
  { id: 'M-04', describes: 'UNC: separators forced to match again (F16-05)',
    find: 'pattern: /' + SEP + '{2}' + NOTSEP + '+' + SEP + NOTSEP + '*/',
    replace: 'pattern: /' + B2 + B2 + '[^' + B2 + BS + 's]+' + B2 + '[^' + B2 + BS + 's]*/' },
  { id: 'M-05', describes: 'UNC: tail made mandatory (the C23 hole)',
    find: SEP + NOTSEP + '*/ },',
    replace: SEP + NOTSEP + '/ },' },
  { id: 'M-06', describes: 'unix path: case flag removed',
    find: BS + '/mnt' + BS + '/)/i',
    replace: BS + '/mnt' + BS + '/)/' },
  { id: 'M-07', describes: 'email: local part back to ASCII-only',
    find: '[^' + BS + 's@<>()' + BS + '[' + BS + ']"]{1,64}@',
    replace: '[A-Za-z0-9._%+-]{1,64}@' },
  { id: 'M-08', describes: 'email: domain bound lowered so real addresses escape (F16-02)',
    find: '.-]{0,253}',
    replace: '.-]{0,12}' },
  { id: 'M-09', describes: 'email: IPv6 literal tag dropped (F16-06)',
    find: BS + '[(?:[Ii][Pp][Vv]6:)?[0-9A-Fa-f:.]{2,45}' + BS + ']',
    replace: BS + '[[0-9A-Fa-f:.]{2,45}' + BS + ']' },
  { id: 'M-10', describes: 'email: quoted local part branch disabled',
    find: '|"[^"]{0,64}"@',
    replace: '|"(?!)"@' },
  { id: 'M-11', describes: 'markup: back to DOCTYPE only',
    find: '<!--|<!' + BS + '[CDATA' + BS + '[|<![A-Za-z]|<' + BS + '?[A-Za-z=]|' + BS + ']' + BS + ']>',
    replace: '<!--|<!' + BS + '[CDATA' + BS + '[|<!DOCTYPE|<' + BS + '?[A-Za-z]' },
  { id: 'M-12', describes: 'deepFreeze neutered (every frozen contract goes shallow)',
    // Downgrading one export no longer tests anything: HARD_REJECT_RULES and
    // ADVISORY_LINT_RULES are deep-frozen too and share the same rule objects,
    // so they re-freeze them. Target the function itself.
    find: '  function deepFreeze(value) {',
    replace: '  function deepFreeze(value) { return value; } function deepFreezeUnused(value) {' },
  { id: 'M-13', describes: 'checkedAt contract left unfrozen',
    find: 'CHECKED_AT_PATTERN: deepFreeze(CHECKED_AT_PATTERN)',
    replace: 'CHECKED_AT_PATTERN: CHECKED_AT_PATTERN' },
  { id: 'M-14', describes: 'yen fold: round-10 currency exception restored',
    find: fold(YEN),
    replace: fold(YEN, '(?!' + BS + 'd)') },
  { id: 'M-15', describes: 'yen fold: fullwidth yen dropped',
    find: fold(YEN),
    replace: fold('[' + U('00a5') + ']') },
  { id: 'M-16', describes: 'closure convergence guard lowered to 4',
    find: 'guard > 16',
    replace: 'guard > 4' },
  { id: 'M-17', describes: 'invisible class: Default_Ignorable dropped',
    find: BS + 'p{Cf}' + BS + 'p{Default_Ignorable_Code_Point}',
    replace: BS + 'p{Cf}' },
  { id: 'M-18', describes: 'control characters: U+2028/2029 dropped',
    find: U('007F') + '-' + U('009F') + U('2028') + U('2029') + ']',
    replace: U('007F') + '-' + U('009F') + ']' },

  // ---- Human Gate §8 surface ------------------------------------------
  { id: 'M-19', describes: 'advisory demotion reverted: www throws again',
    find: "{ name: 'www', advisory: true,",
    replace: "{ name: 'www', advisory: false," },
  { id: 'M-20', describes: 'advisory demotion reverted: provider rule throws again',
    find: "{ name: 'known-private-provider', advisory: true,",
    replace: "{ name: 'known-private-provider', advisory: false," },
  { id: 'M-21', describes: 'lint returns no warnings at all',
    find: '        warnings.push({ rule: entry.name,',
    replace: '        if (false) warnings.push({ rule: entry.name,' },
  { id: 'M-22', describes: 'advisory message emptied (warning becomes mute)',
    find: "      message: 'text contains a www-style hostname; human review required before publication' },",
    replace: "      message: 'x' }," },
  { id: 'M-23', describes: 'QD-J17: consumer computes warnings then drops them',
    file: 'tools/evidence-publication-lint.mjs',
    find: '  const withWarnings = results.filter((r) => r.warnings.length > 0);',
    replace: '  const withWarnings = [];' },
  { id: 'M-24', describes: 'QD-J17: the safety disclaimer is dropped from the report',
    file: 'tools/evidence-publication-lint.mjs',
    find: "  lines.push('An empty advisory list is NOT proof that the prose is safe to publish.');",
    replace: "  lines.push('');" },
  { id: 'M-25', describes: 'QD-J16: caseId length bound widened back past the token threshold',
    file: 'project-config/miyoshi.js',
    find: 'var CASE_ID_PATTERN = /^[A-Za-z][A-Za-z0-9_-]{0,26}$/;',
    replace: 'var CASE_ID_PATTERN = /^[A-Za-z][A-Za-z0-9_-]{0,47}$/;' },
  { id: 'M-26', describes: 'QD-J16: filename-like caseId rejection removed',
    file: 'project-config/miyoshi.js',
    find: '    if (FILENAME_LIKE_CASE_ID_PATTERN.test(caseObj.caseId)) {',
    replace: '    if (false && FILENAME_LIKE_CASE_ID_PATTERN.test(caseObj.caseId)) {' },
  { id: 'M-27', describes: 'publication lint stops collecting caseId (§10)',
    file: 'tools/evidence-publication-lint.mjs',
    find: "  'caseId'                      // published identifier",
    replace: "  'caseId_disabled'             // published identifier" },
  { id: 'M-28', describes: 'FP-01: lint default roots hand-listed again',
    file: 'tools/evidence-publication-lint.mjs',
    find: '  return sources;\n}',
    replace: "  return { miyoshi: sources.miyoshi };\n}" },
  { id: 'M-29', describes: 'inventory path grammar: array index emitted as .N not [N]',
    file: 'tools/evidence-publication-lint.mjs',
    find: "node.forEach((v, i) => walk(v, path + '[' + i + ']'));",
    replace: "node.forEach((v, i) => walk(v, path + '.' + i));" },
  { id: 'M-30', describes: 'inventory path grammar: leading segment separator dropped',
    file: 'tools/evidence-publication-lint.mjs',
    find: "      const here = path + '.' + key;",
    replace: "      const here = path + '..' + key;" },

  // ---- Phase 2K Wave 1: verification infrastructure -------------------
  // Retargeted in Wave 3. It used to flip guard-diff's INADMISSIBLE, which no
  // longer exists because the quarantine was lifted on measurement (D-008). The
  // operator's intent survives unchanged: a non-admissible instrument must not
  // be silently re-admitted. It now aims at the mutation harness, whose
  // DIAGNOSTIC_ONLY is a judgement rather than a measurement -- the case where
  // a silent upgrade would be easiest to miss. Its PATCH-MISS is what revealed
  // that no test pinned any individual admissibility at all.
  { id: 'K1-01', describes: 'silently re-admit a non-admissible instrument',
    file: 'tools/verification/verification-spec.json',
    find: '"admissibility": "DIAGNOSTIC_ONLY"',
    replace: '"admissibility": "ADMISSIBLE"' },
  { id: 'K1-02', describes: 'collapse evidenceClass and admissibility into one check',
    file: 'tools/verification/admissibility.mjs',
    find: "export const RESULT_ONLY_STATES = Object.freeze(['PASS', 'FAIL', 'ERROR']);",
    replace: "export const RESULT_ONLY_STATES = Object.freeze([]);" },
  { id: 'K1-03', describes: 'remove inputDigest from the provenance contract',
    file: 'tools/verification/admissibility.mjs',
    find: "  'inputDigest',\n  'command',",
    replace: "  'command'," },
  { id: 'K1-04', describes: 'project-state maps readySlotCount from requiredSlotCount',
    file: 'tools/verification/project-state-probe.mjs',
    find: '      readySlotCount: closure.readySlotCount,',
    replace: '      readySlotCount: closure.requiredSlotCount,' },
  { id: 'K1-05', describes: 'project-state drops the category count',
    file: 'tools/verification/project-state-probe.mjs',
    find: "      readyCategoryCount: closure.readyCategoryCount,\n      categoryCount: closure.categoryCount,",
    replace: "      readyCategoryCount: closure.readyCategoryCount," },
  { id: 'K1-06', describes: 'project-state emits a publicDescription',
    file: 'tools/verification/project-state-probe.mjs',
    find: '        mode: Miyoshi.dimensions.mode,',
    replace: '        mode: Miyoshi.dimensions.mode,\n        publicDescription: Miyoshi.dimensions.defaultW.evidence.publicDescription,' },
  { id: 'K1-07', describes: 'verifier package prescribes a verdict',
    file: 'tools/verification/verifier-package.mjs',
    find: '    schemaVersion: SCHEMA_VERSION,\n    repository: spec.repository,',
    replace: "    schemaVersion: SCHEMA_VERSION,\n    expectedVerdict: 'PASS',\n    repository: spec.repository," },
  { id: 'K1-08', describes: 'verifier package silently returns [] changed files',
    file: 'tools/verification/verifier-package.mjs',
    find: "  if (files.length === 0) {",
    replace: "  if (false) {" },
  { id: 'K1-09', describes: 'manifest omits sharedDependencies',
    file: 'tools/verification/manifest.mjs',
    find: '      sharedDependencies: i.sharedDependencies || [],',
    replace: '' },
  { id: 'K1-10', describes: 'unknown schemaVersion accepted',
    file: 'tools/verification/admissibility.mjs',
    find: '  if (value !== SCHEMA_VERSION) {',
    replace: '  if (false) {' },
  { id: 'K1-11', describes: 'instrument source digest derived from mtime',
    file: 'tools/verification/manifest.mjs',
    find: ".update(readFileSync(join(ROOT, rel))).digest('hex') + '\\n');",
    replace: ".update(String(statSync(join(ROOT, rel)).mtimeMs)).digest('hex') + '\\n');" },
  { id: 'K1-12', describes: 'changedFiles left unsorted (non-deterministic)',
    file: 'tools/verification/verifier-package.mjs',
    find: "  const files = out.split('\\n').map((s) => s.trim()).filter(Boolean).sort();",
    replace: "  const files = out.split('\\n').map((s) => s.trim()).filter(Boolean).reverse();" },
  // --- Phase 2K Wave 2: publication-lint discovery independence (QD-J23) ---
  { id: 'K2-01', describes: 'lint discovery back to non-recursive (QD-J23 itself)',
    file: 'tools/evidence-publication-lint.mjs',
    find: '      if (entry.isDirectory()) { stack.push(rel); continue; }',
    replace: '      if (entry.isDirectory()) { continue; }' },
  { id: 'K2-02', describes: 'nested root name collapsed to basename (location lost)',
    file: 'tools/evidence-publication-lint.mjs',
    find: "    sources[rel.replace(/" + BS + ".js$/, '')] = require(posixPath.join(base, rel));",
    replace: "    sources[rel.split('/').pop().replace(/" + BS + ".js$/, '')] = require(posixPath.join(base, rel));" },
  { id: 'K2-03', describes: 'symlinks followed (cycle / escapes the tree)',
    file: 'tools/evidence-publication-lint.mjs',
    find: '      if (entry.isSymbolicLink()) continue;',
    replace: '      if (false) continue;' },
  { id: 'K2-04', describes: 'config module load failure swallowed (inventory shrinks quietly)',
    file: 'tools/evidence-publication-lint.mjs',
    find: "    sources[rel.replace(/" + BS + ".js$/, '')] = require(posixPath.join(base, rel));",
    replace: "    try { sources[rel.replace(/" + BS + ".js$/, '')] = require(posixPath.join(base, rel)); } catch (e) { continue; }" },
  { id: 'K2-05', describes: 'discovery order not pinned (report non-deterministic)',
    file: 'tools/evidence-publication-lint.mjs',
    find: '  return found.sort();',
    replace: '  return found.sort().reverse();' },
  { id: 'K2-06', describes: 'extension filter dropped (non-modules required)',
    file: 'tools/evidence-publication-lint.mjs',
    find: "      if (entry.isFile() && rel.endsWith('.js')) found.push(rel);",
    replace: '      if (entry.isFile()) found.push(rel);' },
  { id: 'K2-07', describes: 'discovery stops after the first module found',
    file: 'tools/evidence-publication-lint.mjs',
    find: "      if (entry.isFile() && rel.endsWith('.js')) found.push(rel);",
    replace: "      if (entry.isFile() && rel.endsWith('.js') && found.length === 0) found.push(rel);" },
  { id: 'K2-08', describes: 'QD-J23 experiment stops restoring the tree',
    file: 'tools/verification/experiments/lint-discovery-depth.mjs',
    find: '  rmSync(PROBE_DIR, { recursive: true, force: true });',
    replace: '  if (false) rmSync(PROBE_DIR, { recursive: true, force: true });' },
  // --- Phase 2K Wave 3: differential / mutation instrument reproducibility ---
  { id: 'K3-01', describes: 'corpus dot threat list shrinks (P2K-F01 relapse)',
    file: 'tools/guard-diff/corpus.mjs',
    find: "'" + U('2e33') + "', '" + U('0387') + "', '" + U('06d4') + "'",
    replace: "'" + U('2e33') + "', '" + U('06d4') + "'" },
  { id: 'K3-02', describes: 'corpus extension threat list shrinks',
    file: 'tools/guard-diff/corpus.mjs',
    find: "'zip', 'rar', '7z'",
    replace: "'zip', '7z'" },
  { id: 'K3-03', describes: 'constantCoverage stops reporting what production lost',
    file: 'tools/guard-diff/corpus.mjs',
    find: '    extraInCorpus: mine.filter((x) => theirs.indexOf(x) === -1)',
    replace: '    extraInCorpus: []' },
  { id: 'K3-04', describes: 'constantCoverage stops reporting what production gained',
    file: 'tools/guard-diff/corpus.mjs',
    find: '    missingFromCorpus: theirs.filter((x) => mine.indexOf(x) === -1),',
    replace: '    missingFromCorpus: [],' },
  { id: 'K3-05', describes: 'differential drops the re-attribution bucket (P2K-F03 relapse)',
    file: 'tools/guard-diff/differential.mjs',
    find: '    else if (b && h && b !== h) reattributed.push([text, b, h]);',
    replace: '' },
  { id: 'K3-06', describes: 'rule coverage gaps always reported as none',
    file: 'tools/guard-diff/differential.mjs',
    find: '  return names.filter((name) => !attribution[name]);',
    replace: '  return [];' },
  { id: 'K3-07', describes: 'differential exits 0 despite an unexercised rule',
    file: 'tools/guard-diff/differential.mjs',
    find: '  return (regressions > 0 || coverageGaps > 0) ? 1 : 0;',
    replace: '  return regressions > 0 ? 1 : 0;' },
  { id: 'K3-08', describes: 'control-character corpus axis removed (P2K-F02 relapse)',
    file: 'tools/guard-diff/corpus.mjs',
    find: '  CONTROL_HOSTS.forEach((host) => {',
    replace: '  [].forEach((host) => {' },
  { id: 'K3-09', describes: 'control-class non-members dropped from the corpus',
    file: 'tools/guard-diff/corpus.mjs',
    find: "  const CONTROL_NON_MEMBERS = ['" + BS + "t', '" + BS + "n', '" + BS + "r'];",
    replace: '  const CONTROL_NON_MEMBERS = [];' },
  { id: 'K3-10', describes: 'suite verdict stops requiring a TAP summary (P2K-F09 relapse)',
    file: 'tools/guard-diff/suite-verdict.mjs',
    find: '  if (!passLine || !failLine) {',
    replace: '  if (false) {' },
  { id: 'K3-11', describes: 'hostile env keys no longer stripped from the suite child',
    file: 'tools/guard-diff/suite-verdict.mjs',
    find: '  for (const key of HOSTILE_ENV_KEYS) delete out[key];',
    replace: '' },
  { id: 'K3-12', describes: 'suite verdict ignores exit-code / fail-count disagreement',
    file: 'tools/guard-diff/suite-verdict.mjs',
    find: '  if ((failCount > 0) !== (run.exitCode !== 0)) {',
    replace: '  if (false) {' },
  { id: 'K3-13', describes: "suite verdict ignores fail-count / 'not ok' disagreement",
    file: 'tools/guard-diff/suite-verdict.mjs',
    find: '  if ((failCount > 0) !== (failing.length > 0)) {',
    replace: '  if (false) {' },
  { id: 'K3-14', describes: 'advisory coverage always reported as complete',
    file: 'tools/guard-diff/differential.mjs',
    find: '  return names.filter((name) => !seen.has(name));',
    replace: '  return [];' },
  { id: 'K3-15', describes: 'corpus digest drops the record separator (collidable)',
    file: 'tools/guard-diff/corpus.mjs',
    find: "  for (const text of corpus) { h.update(text, 'utf8'); h.update(NUL); }",
    replace: "  for (const text of corpus) { h.update(text, 'utf8'); }" },
  { id: 'K3-16', describes: 'corpus digest made order-insensitive',
    file: 'tools/guard-diff/corpus.mjs',
    find: '  const h = createHash(\'sha256\');',
    replace: "  const h = createHash('sha256'); corpus = [...corpus].sort();" }
];
